# Config for https://github.com/toolmantim/release-drafter
name-template: 'Alpakka $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: ':toolbox: Infrastructure'
    label: 'alpakka-itself'
  - title: 'AMQP'
    label: 'p:amqp'
  - title: 'Apache Solr'
    label: 'p:solr'
  - title: 'Apache HDFS'
    label: 'p:hdfs'
  - title: 'Apache Kudu'
    label: 'p:kudu'
  - title: 'AvroParquet'
    label: 'p:avroparquet'
  - title: 'AWS EventBridge'
    label: 'p:aws-event-bridge'
  - title: 'AWS Lambda'
    label: 'p:aws-lambda'
  - title: 'AWS Kinesis'
    label: 'p:kinesis'
  - title: 'AWS S3'
    label: 'p:aws-s3'
  - title: 'AWS SNS'
    label: 'p:aws-sns'
  - title: 'AWS SQS'
    label: 'p:aws-sqs'
  - title: 'Azure Storage Queue'
    label: 'p:azure-storage-queue'
  - title: 'Cassandra'
    label: 'p:cassandra'
  - title: 'Comma-separated Values (CSV)'
    label: 'p:csv'
  - title: 'Couchbase'
    label: 'p:couchbase'
  - title: 'Dynamo DB'
    label: 'p:dynamodb'
  - title: 'Elasticsearch'
    label: 'p:elasticsearch'
  - title: 'File'
    label: 'p:file'
  - title: 'FTP'
    label: 'p:ftp'
  - title: 'Geode'
    label: 'p:geode'
  - title: 'Google Cloud BigQuery'
    label: 'p:google-cloud-bigquery'
  - title: 'Google Cloud Pub/Sub'
    label: 'p:google-cloud-pub-sub'
  - title: 'Google Cloud Pub/Sub gRPC'
    label: 'p:google-cloud-pub-sub-grpc'
  - title: 'Google Cloud Storage'
    label: 'p:google-cloud-storage'
  - title: 'Google FCM (Firebase)'
    label: 'p:google-fcm'
  - title: 'HBase'
    label: 'p:hbase'
  - title: 'InfluxDB'
    label: 'p:influxdb'
  - title: 'IronMQ'
    label: 'p:ironmq'
  - title: 'JDBC'
    label: 'p:jdbc'
  - title: 'JMS'
    label: 'p:jms'
  - title: 'Json streaming'
    label: 'p:json-streaming'
  - title: 'MongoDB'
    label: 'p:mongodb'
  - title: 'MQTT'
    label: 'p:mqtt'
  - title: 'MQTT Streaming'
    label: 'p:mqtt-streaming'
  - title: 'OrientDB'
    label: 'p:orientdb'
  - title: 'Pravega'
    label: 'p:pravega'
  - title: 'Reference'
    label: 'p:reference'
  - title: 'Server-sent events (SSE)'
    label: 'p:sse'
  - title: 'Simple Codecs'
    label: 'p:recordio'
  - title: 'Slick'
    label: 'p:slick'
  - title: 'Spring Web'
    label: 'p:spring-web'
  - title: 'Text'
    label: 'p:text'
  - title: 'UDP'
    label: 'p:udp'
  - title: 'Unix Domain Socket'
    label: 'p:unix-domain-socket'
  - title: 'XML'
    label: 'p:xml'

change-template: '- $TITLE [#$NUMBER](https://github.com/akka/alpakka/issues/$NUMBER) by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  # :mega: Alpakka $NEXT_PATCH_VERSION released!

  ### See the full Release Notes in the [Alpakka documentation](https://doc.akka.io/docs/alpakka/2.0/release-notes/2.0.x.html).

  ## Changes

  $CHANGES

  ## :bow: Credits
  Special thanks to the following contributors who helped with this release: $CONTRIBUTORS
